services:
  redis:
    image: redis:latest
    container_name: redis
    command: redis-server --requirepass abcd1234
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  workers:
    build:
      context: .
      dockerfile: Dockerfile.worker
    container_name: workers
    env_file:
      - packages/workers/.env
    depends_on:
      - redis

volumes:
  redis_data:
